name: highlighter_coachmark
description: Coach Mark shows provided tips or inctructions in overlay by blurring background and highlighting target element.
version: 0.0.4
author:  Marina Kuznetsova <marica.tim@gmail.com>
homepage: https://github.com/marica27/highlighter-coachmark
maintainer: Marina Kuznetsova (@marica27)

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
